ALTER TABLE messages MODIFY COLUMN content LONGTEXT NULL;
ALTER TABLE messages MODIFY COLUMN status VARCHAR(20) DEFAULT 'sent';
ALTER TABLE messages ADD COLUMN duration VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN bio VARCHAR(150) NULL;